---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: chat-db
  namespace: default
spec:
  encryptedData:
    CASSANDRA_PASSWORD: AgAarMNbsra0STEUIbRk2Z9rTt+E158aqmd3FgmkQiDPPib7RgLaZgN9fiRap1+5G7nCEecLqD6YUj7UowT1sDdcFQdCGak1i5UrGeC3T3aUAm5z6yYWrs9o+ZH3zUATRysVPGwfOhv8O9ZcAz7YvqyxTUjob5z3ln7Hce+zNupDeKnny4jrW1zI6IWrcgf0f9VUX1hwYy6QQYkr/XfQ4aAmX6J9do0d9SMdTcZL5hhsSvTnP0O9V3+bToGE4saRKvgowDR4jctbnTDa7biqIsvbEZjPb0lRgRFGSohMai/5ByU2rEzfiyz3/JnZSxulwj4UUF+FgaiGlD6sCE+O+UGn0wb1f+jn5YOsp2roXyYRD+M0BaG8z8bu49jL7h1rFx1QPwlK4tpCpHFPJ0ItQqFP+/3RNEaqaR8+VGuxmp7Mpk3eJlO8uRwkByWPIPdGPP+bD7+8ex8uRr6dWrEu/eZBMJ6+MivDLqNC2U2YFSMMN1jwFiHIZTnVon8SvuHBBTjeOZjHD6wVwhOuVV4GYhXumxMDfOffEhPRqC7kgAgH27emD4uLw8HtZZ1HR09hvgVTXBEEgJNCItEY6SEP/VwxIKgKneqZQZyudn/D2PJqA4W2fkrA7p1Z766yiN1bEA5Ozo0bQ5BNscHtsiPoobK1aWQx3pS7Y6yX8jhrun43AgiV39KBSSnEE21cgNRXUBUseTE4HF6dymq8k9KZWFJCcQnfXnNuWtxik/6Sn2GTh5vOsrpotS5rQSr87324Pvs=
    CASSANDRA_USERNAME: AgCDzk1knxjkdA608qKqUEzQfkovgWGNBmqM5wPnr6tDYfnuymBXWIRetRGnUqyLf4mmmbPoFZN6HqyKEFo2B+Uyvon0cBfzqM+40VfWmhVjxHLJHzmCcot03lAde9JWQjZrP5piYjW2HoDEKNCWAUiSjUMkUzKvLtoHbjezDJONQ5eRBDX1pVS1GL1MhLzy140ecugoY8I+hSuPldVKOQyO9jdpNR1y7HrfmnEgEAC9YykcMSMLXKn3Ec2ZPwIav0qtrLjxGwtz9TBM93hfTI5kp3A8ebOPVrr/qPeLmsavER47wLRrCPzn2i0GgCp7tjItvBIA8QYrFTB5r4IesFvF/F7YzRcFqWw+pSFuEJCXOxTt8Gbyp07J21OXrZJzd6VCRQfuVrAgiErGgW9PE95c3kfLnpFPjBjonMD0mFpARHU8diNEVXk94Q8Iq6VjxLk7Mh0OgP+UFCFfsoG2RYIu/N7RrjdMXCMYbiwzv7WBHO84PH8rE/Yz2X7saN9R6WF3WNwt782ppJ6OTFOYwrcwbl/wEdP6RzFBAmGN5xo7YCMfp37yFx8mvVJ7Uvoh5DOw/xxvUQDsL3Rr7RzjQq7tVQrTM3P2whFz4LORL9rvlPKqMJOkcGwGXyGIqyH95UdB87rPR0ovDsj/1gDBEmZ7HlB+DeQicMpxsAVGGETHI5BXMTLUHgdA6MJVlWJ60aJEFHmC+M6sLA==
  template:
    metadata:
      name: chat-db
      namespace: default
