---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hello-secret
  namespace: default
spec:
  encryptedData:
    message: AgAv5q1N2hkAXIIxutYhDXu+yREpL+XpY+QbIV6gSZz/VzYRR6FFuy1zY3qZWy3eFMNbrJGT/UCC9ki6h1bjSc0/Xnli/twa4UnsNVPvttu7XvseUAUT6qU9viGc4HW7fPnJZ94DTlAdHB+Nuy+gtnfA3NaKyQmY5AhCOWZ+PU2j82blrPO1D63/XM6tqz14CDX3ELdKYjrIURy8SfqcCyauHt2lN9Ak/dtFUzTDsebU36amcJ0OGYxW1o2VcGR6ixzoj7RbiiaiQl6zdh5+wsMfX2afSyoUuXpZSbh5gM2xxcfjymotRxTCgiLTSZ3xG3RrC0q9+07UTcNJ4ZOX0u1LyNR+JAz/NJGO0qfII/r6FmoomkbDke2+rrKKazbli/YBNi5biKAokYpBoSaKKrbDJTFquKHmSgvoxVqqwpEJXD2jNjts4yRrrXBD8NBQCCNFmk2g5yc37TBrqrC0xvbjdo20BKuhDgHA9oKGO/6bKkFrBBl4m3ZJDfNOGlagyDBygjq5bqjdt/aPWNXo4fIy+IbzXV3iDslxtZdFvS734gtXRDFd3hMV5Kk8SSyejGCa7LQ6G9QXCnEqDGaUhJxmo2yf4juMQlf8beUdjitNtSk0Br4e1M9P1EGzfd8YZWNxalBZ89DYy4Ba432UrMx2prymvIXrAkOS5jEuGLROqrNurAJ9imEI3SRB/hg96fJ1FY8+1Ja+vA==
  template:
    metadata:
      name: hello-secret
      namespace: default
