apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat
                port:
                  number: 8000
