---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCRqMnJNGF2i00p5MDvj4/kjlomm20g3tJ5HWPBLYJNlTbKHmYI72FRy6TTHTYSJaul9Zc0/GTCM0yhr7m8lk+/rmbtD4N859oY9mQaQzgM8drU9ElJl4VCT9EE/FHK+YEufb1aXnPeGI/JkvzOxwEfKYLUfmvZOcihjszKLPGuKYYrt6OkwigU+GPkpQkIMvd55kHA1FSP7kMZvl9byQMnNecJKffwcC5eMjKuISaGdbfeuMeILHk/xbsMneGNn375t12cagDCUIWvHGR/aRxonE4YlKav7eKz1jjNYBD6AVYAlTRcIBk1xza6U0bMEufzmD5MrHR31HZpkdl9z4Ic4ankDIvtxzgJ45yK2G2+bgUaxHBe+PFQ1eH5dnS2bstkw0+w/Eco3xmgUAjvR3bH75BSU2Qm/FCl8ehJW9LXOY4MyDVZtyIzelMqSQDZFuj53lcYHqvihSDzcszp2fp/rHraS7hvNfgaNdqEX7WcUjE7EPBgskfDrbGjsXpRD8Y+6HYMeswVNoAzpWx2QNNvuy5Z5KSIJotsL03N0/5j4Phfkzu2mwI6QoQEONXmPtfo0H4uyEU8nD3Ia2CLEk1eccAiiUtCIUVJ84frCIA6zeWdCOfECaJV0635RrMhurgw4rSUZhMe8IK5FQzxBePloVqddyqFBPFjySUJJXtXyr9fSMdwhREdS/Hns0lW/xI1xGNsgDCLei7CzQ==
    admin-user: AgCi7zXAfZKNwHobE/r+jQJR4aehN7ow5UFp21/6WMA4o8gP6uM56GALfFNjKR4LOLiSaPgTGFM9YPMtDqfxKy10ivjkE1jgAAOCBaP46cCmCarhXm2pd1Q6x+5xbxOhHWlc2wjDM4hVDADDRPhfuvpNBXYDvH+v22y/P0BRlc9outYmoIEabHDU1a/3Xzub5EmEJgiR71+VrQYk2pgtgOg3wMBIID9U8mQFW5ByUquTWt+DjSF/mLkMRUVveo7VPEI7dU9qV9I0zLSzdAu6w5OrWrx73BvS7EGbRNFHzhfTQBLP66DsbR/L0beEUQNnVQyuR2oJz7lyHl5RCsB/FMHfBZOvwQh5KH1IGm8nAAfoftw7gz5tZBhKfenNvVAoncCrE7RDaegmfSKHajYy9QtGlx7LqUz5qTVh3tfgNPfS1+N3cArK7Jk31WF/3au1Q0JUV4SQ5roLU8eAxuxdIn/AIJ7cSGBGE3SMuPiKKxYkkCmr3wXLtlH3TFii8jwmLkwAPibu12N9TPlQX7MAVAD2ByO+5nm1+1Og03kSse8HDXGg1I3sk6t6JYcdSxZ1DPW8U9uwZS1bSnN+OOv8OfoA6EuhmsHbWdi9MxE44caDMHiPtzMPAKaK/tzjNMSYBGmeQmw01i/KIlq++TLWJZxCUccOaXY9SToPK0sTfXRLHK+PbdQaSHstzySi299oYvPBDba93w==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
